#!/usr/bin/env bash

# stop if we encounter an error
set -e

# check args
if [ $# -ne 1 ]; then
    echo "usage: $0 <build-workspace>"
    exit 1
fi

# setup variables
BUILD_WORKSPACE="$1"

# build samples
./build-sample "${BUILD_WORKSPACE}" "$PWD"

# remove build files
PROJECT_NAME=Playground
SAMPLES_WORKSPACE="${BUILD_WORKSPACE}/Samples"
PROJECT_WORKSPACE="${SAMPLES_WORKSPACE}/${PROJECT_NAME}"

rm -f "${PROJECT_WORKSPACE}/build-all"
rm -f "${PROJECT_WORKSPACE}/build-sample"
rm -rf "${PROJECT_WORKSPACE}/.git"
rm -f "${PROJECT_WORKSPACE}/.gitignore"
